language: node_js
node_js:
    - "10.15.0"

addons:
  apt:
    packages:
      - docker-ce

env:
# one line for one build job!
  - CI_ENV=travis NODE_ENV=travis SHA=$(git rev-parse HEAD)


services:
  - mysql
  - docker

before_install:
  # check Docker version
  - docker --version
  # create db
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ac_twitter_workspace_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
  # db migrate
  - docker-compose -f docker-compose.test.yml run oasis npx sequelize db:migrate

script:
  # run test
  - docker-compose -f docker-compose.test.yml up --exit-code-from oasis

after_success:
  # build production images latest and SHA
  - docker image build -t jackson162/oasis-prod:latest -t jackson162/oasis-prod:$SHA --target prod
  # login Docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # upload images
  - docker push jackson162/oasis-prod:latest
  - docker push jackson162/oasis-prod:$SHA

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-2"
  app: "oasis-e-commerce"
  env: "Oasisecommerce-env"
  bucket_name: "elasticbeanstalk-us-east-2-232056437055"
  bucket_path: "oasis-e-commerce"
  on:
    branch: master
