version: '3.1'
# compose for Travis CI
services:
  oasis:     
    build: 
      context: .
      target: test
    image: jackson162/oasis-test
    networks:
      # travis default is Linux, connect to host network,
      # so container can access DB on docker host via 127.0.0.1
      - host
    ports:
      - 9229:9229
      - 3000:3000   
    environment:
      CI_ENV: travis
      SESSION_SECRET: $SESSION_SECRET
      MY_MAIL: $MY_MAIL
      MY_PASS: SKIP
      MERCHANT_ID: $MERCHANT_ID
      HASH_KEY: $HASH_KEY
      HASH_IV: $HASH_IV
      IMGUR_CLIENT_ID: $IMGUR_CLIENT_ID
      BASE_URL: $BASE_URL